### ISSUE TITLE
npm version is out of date

### ISSUE THREAD

**Issue by dave-vazquez** [sonnylazuardi/react-native-bouncing-preloader#10]
Last publication was made 3 years ago and there have been a few changes added since then. 

https://www.npmjs.com/package/react-native-bouncing-preloader/v/1.0.1

**Comment by dave-vazquez** [comment]
@sonnylazuardi Can you publish the latest version? Can't run a yarn or npm install with the most recent changes.

**Comment by alz10** [comment]
We can't install the latest merge about `useNativeDriver`

**Comment by sonnylazuardi** [comment]
Just published in the new package because I lost my 2FA for my previous account 😢 

```import BouncingPreloader from 'react-native-bouncing-preloaders';```

https://snack.expo.io/@sonnylazuardi/testing-preloader

**Comment by dave-vazquez** [comment]
Thanks @sonnylazuardi 🙂

**Comment by KrisLau** [comment]
@sonnylazuardi Will you be creating a github for that new package or should new issues & commits just be directed here?
